export const categories = [
  "All",
  "Home Decor",
  "Toys & Figures",
  "Accessories",
  "Office",
  "Custom Parts",
];

export const products = [
  {
    id: 1,
    name: "Cyber-Bongo Planter",
    price: 45.00,
    category: "Home Decor",
    image: "/images/Generated Image November 08, 2025 - 10_45PM_nobg.png",
    description: "A futuristic planter with geometric lego-like textures.",
  },
  {
    id: 2,
    name: "Neon Block Lamp",
    price: 120.00,
    category: "Home Decor",
    image: "/images/Generated Image November 08, 2025 - 8_36PM_nobg.png",
    description: "Modular lamp shade that snaps together.",
  },
  {
    id: 3,
    name: "Robo-Rex Figure",
    price: 35.00,
    category: "Toys & Figures",
    image: "/images/Generated Image November 08, 2025 - 8_42PM_nobg.png",
    description: "Articulated T-Rex with a cybernetic aesthetic.",
  },
  {
    id: 4,
    name: "Hex-Grip Phone Stand",
    price: 15.00,
    category: "Office",
    image: "/images/Generated Image November 08, 2025 - 8_45PM_nobg.png",
    description: "Minimalist phone stand with hexagonal grip pattern.",
  },
  {
    id: 5,
    name: "Pixel-Art Coasters",
    price: 25.00,
    category: "Home Decor",
    image: "/images/Generated Image November 08, 2025 - 8_49PM_nobg.png",
    description: "Set of 4 coasters resembling 8-bit pixels.",
  },
  {
    id: 6,
    name: "Mecha-Beetle Model",
    price: 55.00,
    category: "Toys & Figures",
    image: "/images/Generated Image November 08, 2025 - 8_54PM_nobg.png",
    description: "Detailed beetle model with mechanical wings.",
  },
  {
    id: 7,
    name: "Voxel Vase",
    price: 60.00,
    category: "Home Decor",
    image: "/images/Generated Image November 08, 2025 - 8_56PM_nobg.png",
    description: "Vase generated from voxel data, watertight.",
  },
  {
    id: 8,
    name: "Cyber-Keycap Set",
    price: 40.00,
    category: "Accessories",
    image: "/images/Generated Image November 08, 2025 - 8_58PM_nobg.png",
    description: "Custom artisan keycaps for mechanical keyboards.",
  },
  {
    id: 9,
    name: "Modular Desk Organizer",
    price: 30.00,
    category: "Office",
    image: "/images/Generated Image November 08, 2025 - 9_08PM_nobg.png",
    description: "Stackable organizer bins.",
  },
  {
    id: 10,
    name: "Retro-Future Clock",
    price: 85.00,
    category: "Home Decor",
    image: "/images/Generated Image November 08, 2025 - 9_09PM (1)_nobg.png",
    description: "Wall clock with nixie-tube style numerals.",
  },
  {
    id: 11,
    name: "Abstract Geo Sculpture",
    price: 150.00,
    category: "Home Decor",
    image: "/images/Generated Image November 08, 2025 - 9_09PM_nobg.png",
    description: "Limited edition geometric art piece.",
  },
  {
    id: 12,
    name: "Bongo-Bot Action Figure",
    price: 45.00,
    category: "Toys & Figures",
    image: "/images/Generated Image November 08, 2025 - 9_10PM_nobg.png",
    description: "The mascot of the future, fully posable.",
  },
];
